variables:
    AUDIT_AWS_CLOUDTRAIL_ALERT_LIST:
        description: "Which alerts would you like to check for? Default is all Cloudtrail alerts."
        required: true
        type: array
        default:
            - cloudtrail-service-disabled
            - cloudtrail-trail-with-global
            - cloudtrail-inventory
    AUDIT_AWS_CLOUDTRAIL_ALLOW_EMPTY:
        description: "Would you like to receive empty reports? Options - true / false. Default is false."
        required: true
        type: boolean
        default: false
    AUDIT_AWS_CLOUDTRAIL_SEND_ON:
        description: "Send reports always or only when there is a change? Options - always / change. Default is change."
        required: true
        type: string
        default: "change"
    AUDIT_AWS_CLOUDTRAIL_ALERT_RECIPIENT:
        description: "Enter the email address(es) that will receive notifications. If more than one, separate each with a comma."
        required: false
        type: string
        default:
    AUDIT_AWS_CLOUDTRAIL_REGIONS:
        description: "List of AWS regions to check. Default is us-east-1,us-east-2,us-west-1,us-west-2,eu-west-1."
        required: true
        type: array
        default:
            - us-east-1
            - us-east-2
            - us-west-1
            - us-west-2
            - eu-west-1
    AUDIT_AWS_CLOUDTRAIL_ROLLUP_REPORT:
        description: "Would you like to send a rollup Cloudtrail report? This is a short email that summarizes the number of checks performed and the number of violations found. Options - notify / nothing. Default is nothing."
        required: true
        type: string
        default: "nothing"
    AUDIT_AWS_CLOUDTRAIL_HTML_REPORT:
        description: "Would you like to send a full Cloudtrail report? This is an email that details any violations found and includes a list of the violating cloud objects. Options - notify / nothing. Default is notify."
        required: true
        type: string
        default: "nothing"
    AUDIT_AWS_CLOUDTRAIL_OWNER_TAG:
        description: "Enter an AWS tag whose value is an email address of the owner of the Cloudtrail object. (Optional)"
        required: false
        type: string
        default: "NOT_A_TAG"
